// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO73b1gMY1hYegJ2_lALVZrCGHrSLY3x0',
    appId: '1:247410475155:web:7fc4315ec59049df0e0d66',
    messagingSenderId: '247410475155',
    projectId: 'chat-app-2b068',
    authDomain: 'chat-app-2b068.firebaseapp.com',
    storageBucket: 'chat-app-2b068.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXTk2IbPhkctvPSFWImHPqXZ2JOl27FEI',
    appId: '1:247410475155:android:642603cafe2d97b90e0d66',
    messagingSenderId: '247410475155',
    projectId: 'chat-app-2b068',
    storageBucket: 'chat-app-2b068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIPlkgd3ciiLYN0pn3cXdldKFejTdGcpg',
    appId: '1:247410475155:ios:4e642c319d9693770e0d66',
    messagingSenderId: '247410475155',
    projectId: 'chat-app-2b068',
    storageBucket: 'chat-app-2b068.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIPlkgd3ciiLYN0pn3cXdldKFejTdGcpg',
    appId: '1:247410475155:ios:4e642c319d9693770e0d66',
    messagingSenderId: '247410475155',
    projectId: 'chat-app-2b068',
    storageBucket: 'chat-app-2b068.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO73b1gMY1hYegJ2_lALVZrCGHrSLY3x0',
    appId: '1:247410475155:web:e1bbd61d605c16f10e0d66',
    messagingSenderId: '247410475155',
    projectId: 'chat-app-2b068',
    authDomain: 'chat-app-2b068.firebaseapp.com',
    storageBucket: 'chat-app-2b068.appspot.com',
  );

}